# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
House.destroy_all
Vassal.destroy_all
Character.destroy_all

    arryn = House.create(name: "Arryn",sigil: "Sigil/arryn.png",words: "As High As Honor",seat: "The Eyrie",region: "The Vale of Arryn")
    frey = House.create(name: "Frey",sigil: "Sigil/frey.png",words: "We Stand Together",seat: "The Twins",region: "The Riverlands")
    greyjoy = House.create(name: "Greyjoy",sigil: "Sigil/greyjoy.png",words: "We Do Not Sow",seat: "Pyke",region: "Iron Islands")
    lannister = House.create(name: "Lannister",sigil: "Sigil/lannister.png",words: "Hear Me Roar",seat: "Casterly Rock",region: "The Westerlands")
    stark = House.create(name: "Stark",sigil: "Sigil/stark.png",words: "Winter is Coming",seat: "Winterfell",region: "The North")
    tyrell = House.create(name: "Tyrell",sigil: "Sigil/tyrell.png",words: "Growing Strong",seat: "Highgarden",region: "The Reach")
    targaryen = House.create(name: "Targaryen",sigil: "Sigil/targaryen.png",words: "Fire and Blood",seat: "Dragonstone",region: "The Crownlands")
    tully = House.create(name: "Tully",sigil: "Sigil/tully.png",words: "Family, Duty, Honor",seat: "Riverrun",region: "The Riverlands")
    martell = House.create(name: "Martell",sigil: "Sigil/martell.png",words: "Unbowed, Unbent, Unbroken",seat: "Sunspear",region: "Dorne")
    bolton = House.create(name: "Bolton",sigil: "Sigil/bolton.png",words: "Our Blades Are Sharp",seat: "The Dreadfort",region: "The North")
    baratheon = House.create(name: "Baratheon",sigil: "Sigil/baratheon.png",words: "Ours is the Fury",seat: "Storm's End",region: "The Stormlands")


    tarly = tyrell.vassals.create(name: "Tarly",sigil: "Sigil/tarly.png",words: "First in Battle",seat: "Horn Hill",region: "The Reach", noble: true)
    clegane = lannister.vassals.create(name: "Clegane",sigil: "Sigil/clegane.png",words: "...",seat: "Clegane's Keep",region: "The Westerlands", noble: true)
    tarth = baratheon.vassals.create(name: "Tarth",sigil: "Sigil/tarth.png",words: "...",seat: "Evenfall Hall",region: "The Stormlands", noble: true)
    seaworth = stark.vassals.create(name: "Seaworth",sigil: "Sigil/seaworth.png",words: "...",seat: "Cape Wrath",region: "The Stormlands", noble: true)
    selmy = baratheon.vassals.create(name: "Selmy",sigil: "Sigil/selmy.png",words: "...",seat: "Harvest Hall",region: "The Stormlands", noble: true)
    mormont = stark.vassals.create(name: "Mormont",sigil: "Sigil/mormont.png",words: "Here We Stand",seat: "Bear Island",region: "The North", noble: true)
    karstark = bolton.vassals.create(name: "Karstark",sigil: "Sigil/karstark.png",words: "The Sun of Winter",seat: "Karhold",region: "The North", noble: true)
    other = Vassal.create(name: "The Others, the Bastards, the Lowborn, and those from across the Narrow Sea",sigil: "",words: "...",seat: "...",region: "...", noble: false)
    wildling = Vassal.create(name: "The Free Folk",sigil:"",words: "...", region: "The North", noble: false)

    lannister.characters.create(name: "Tyrion Lannister",status: "Alive", img_url:"")
    lannister.characters.create(name: "Jaime Lannister",status: "Alive", img_url:"")
    lannister.characters.create(name: "Cersei Lannister",status: "Alive", img_url:"")
    targaryen.characters.create(name: "Daenerys Targaryen",status: "Khaleesi", img_url:"")
    stark.characters.create(name: "Jon Snow",status: "Alive", img_url:"")
    other.characters.create(name: "Petyr Baelish",status: "Alive", img_url:"")
    mormont.characters.create(name: "Jorah Mormont",status: "Alive", img_url:"")
    stark.characters.create(name: "Sansa Stark",status: "Alive", img_url:"")
    stark.characters.create(name: "Arya Stark",status: "The Girl is No One", img_url:"")
    greyjoy.characters.create(name: "Theon Greyjoy",status: "Alive", img_url:"")
    stark.characters.create(name: "Bran Stark",status: "Alive", img_url:"")
    clegane.characters.create(name: "Sandor Clegane",status: "Alive", img_url:"")
    clegane.characters.create(name: "Gregor Clegane",status: "Ali...dead?", img_url:"")
    baratheon.characters.create(name: "Joffrey Baratheon",status: "Dead", img_url:"")
    stark.characters.create(name: "Catelyn Stark",status: "Dead", img_url:"")
    stark.characters.create(name: "Robb Stark",status: "Dead", img_url:"")
    stark.characters.create(name: "Ned Stark",status: "Dead", img_url:"")
    baratheon.characters.create(name: "Robert Baratheon",status: "Dead", img_url:"")
    targaryen.characters.create(name: "Viserys Targaryen",status: "Dead", img_url:"")
    other.characters.create(name: "Varys",status: "Alive", img_url:"")
    tarly.characters.create(name: "Samwell Tarly",status: "Alive", img_url:"")
    other.characters.create(name: "Bronn",status: "", img_url:"Alive")
    lannister.characters.create(name: "Tywin Lannister",status: "Dead", img_url:"")
    mormont.characters.create(name: "Jeor Mormont",status: "Dead", img_url:"")
    other.characters.create(name: "Khal Drogo",status: "Dead", img_url:"")
    other.characters.create(name: "Gendry Storm",status: "Unknown", img_url:"")
    baratheon.characters.create(name: "Tommen Baratheon",status: "Dead", img_url:"")
    other.characters.create(name: "Jaqen H'ghar",status: "Unknown", img_url:"")
    seaworth.characters.create(name: "Davos Seaworth",status: "Alive", img_url:"")
    other.characters.create(name: "Melisandre",status: "Alive", img_url:"")
    tyrell.characters.create(name: "Margaery Tyrell",status: "Dead", img_url:"")
    baratheon.characters.create(name: "Stannis Baratheon",status: "Dead", img_url:"")
    wildling.characters.create(name: "Ygritte",status: "Dead", img_url:"")
    stark.characters.create(name: "Talisa Stark",status: "Dead", img_url:"")
    tarth.characters.create(name: "Brienne of Tarth",status: "Alive", img_url:"")
    wildling.characters.create(name: "Gilly",status: "Alive", img_url:"")
    bolton.characters.create(name: "Roose Bolton",status: "Dead", img_url:"")
    wildling.characters.create(name: "Tormund Giantsbane",status: "Alive", img_url:"")
    bolton.characters.create(name: "Ramsay Bolton",status: "Dead", img_url:"")
    other.characters.create(name: "Daario Naharis",status: "Alive", img_url:"")
    other.characters.create(name: "Missandei",status: "Alive", img_url:"")
    martell.characters.create(name: "Ellaria Sand",status: "Alive", img_url:"")
    other.characters.create(name: "The High Sparrow",status: "Dead", img_url:"")
    stark.characters.create(name: "Hodor",status: "Hodor", img_url:"")
    selmy.characters.create(name: "Barristan Selmy",status: "Dead", img_url:"")
    tully.characters.create(name: "The Blackfish",status: "Dead", img_url:"")
    tully.characters.create(name: "Edmure Tully",status: "Alive", img_url:"")
